name: 'greeting'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: false
    default: 'World'
runs:
  using: "docker"
  image: './.github/actions/greeting/Dockerfile'
outputs:
  time:
    description: 'The time we greeted you'


