name: Reusable Workflow user
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  job1:
    uses: tanviranadive/test-workflows/.github/workflows/workflow.yaml@main
    with:
      image_name: nginx
      tag: ${{ github.ref_name }}
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: do-something
        id: DoSomething
        run:
          echo "${{ github.workspace }}"
          echo "Triggered in branch ${{ github.ref_name }}"